language: node_js
before_script:
- yarn install
- yarn run build
node_js:
- node
deploy:
  app: x4webm
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: ebTEuRgITP/A2aVAdAg2P1BUw0cLOLoofdjdR+2LaUQvuVfGQharajYbCgRoE/PDolpug2akWraohMl5MfCP5dLBDSqiWIeZdlDQek5v+IhyxBELnDT4AbuKJs7QvTBowGuWGTM4tEvRMjyIDszIZG5d+bts/Fl6bkXQMPv7w3NAQbfKdxIk9Kf7dwVy2KIPf+SWg+v34CSsG9sCvQHrURYLltQeQUAP6pGRaDcxKHtWe1u5ywRMbMfjm4C8zRSuR7Fj6KFmiskM4Fn4Jl5O2XGHlohvP/3HHbH9xFnL91vpaz5qPCCNtYEaFarHZivdr2Nlo4ZUDM/8O5ixdOtwwPKjvblYR/r+UsWn7cbbOQ84pQ3JAddT/LKAPWyZ2iKxW+7/SozIH3ZnidOpLA7YUoescLVNleCIjcuzumChy179PmAkEtgd/Q+Hm3k64mPqtb0BHyVJ/WKDrsl1UINgi6PpvguvexgBxfjJrzHG126bvtAXthBz+cTePJuvo9b42/ExHofZU3ePaHXSrDCoqLEWcKmkx/PKCUV1z1PBzBNMe7X07XSTiYm5M7GYrp+5MVW9AiuI0m8owW/wysUU15Diu0ZCXggPLZkWx5a7a5cbc6iOjd22dom1OeH96IwR/qoPYfjuOY15K0OmI7nPzQoMiX1fjiaMfDhVHW0B3y4=
